### ISSUE TITLE
SQLiteException on CPRecord.delete()

### ISSUE THREAD

**Issue by ghost** [Wackymax/CPOrm#3]
Hello! I'm a developer from Brazil, trying to figure out a bug that surfaced in Crashlytics recently.

Here the stack trace:

```
Fatal Exception: android.database.sqlite.SQLiteException: error code 5: database is locked
       at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:180)
       at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:136)
       at android.content.ContentProviderProxy.delete(ContentProviderNative.java:479)
       at android.content.ContentResolver.delete(ContentResolver.java:822)
       at za.co.cporm.model.CPOrm.delete(CPOrm.java:282)
       at za.co.cporm.model.CPRecord.delete(CPRecord.java:93)
       at za.co.cporm.model.CPRecord.delete(CPRecord.java:88)
       at [My Package] NotificationsHelper$1.onResponse(NotificationsHelper.java:69)
       at [My Package] NotificationsHelper$1.onResponse(NotificationsHelper.java:59)
       at com.android.volley.toolbox.JsonRequest.deliverResponse(JsonRequest.java:65)
       at com.android.volley.ExecutorDelivery$ResponseDeliveryRunnable.run(ExecutorDelivery.java:99)
       at android.os.Handler.handleCallback(Handler.java:605)
       at android.os.Handler.dispatchMessage(Handler.java:92)
       at android.os.Looper.loop(Looper.java:137)
       at android.app.ActivityThread.main(ActivityThread.java:4517)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:511)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:995)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:762)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

And here is `NotificationsHelper.java:69` (which, by the way, extends `CPDefaultRecord<NotificationItem>`):

``` Java
List<NotificationItem> notificationItemList = Select.from(NotificationItem.class).queryAsList();
for (NotificationItem notification : notificationItemList) {
  notification.delete();
}
```

I saw that this error is associated with concurrent access: [https://www.sqlite.org/cvstrac/wiki?p=DatabaseIsLocked](https://www.sqlite.org/cvstrac/wiki?p=DatabaseIsLocked)

This error belongs to the way I'm using the library, defect on the devices (only Samsung devices with Android 4 has presented the error until now) or is it a bug?

**Comment by Wackymax** [comment]
Hi, thanks for the report.  I will have a look at this.  I think write ahead logging is enabled by default, so database locks should not occur, but it could be related to that version of android.

**Comment by Wackymax** [comment]
Hi,

I looked into this a bit.  I cannot think of why this will happen, the only reason it would is if two different threads try to open an access the database.  Which is rather strange because I would assume android creates only one instance of a content provider.  Are you not maybe opening the database somewhere in your application outside of CPOrm?  Is your content provider running in its own process?
